In [1]:
import numpy as np

In [5]:
arreglo_numeros = np.array([[1,2,3],[4,5,6]]) #np.array define arreglos de n dimensiones
print (arreglo_numeros)

[[1 2 3]
 [4 5 6]]


In [3]:
np.zeros((3,4)) # define arreglos de n dimensiones lleno de ceros
np.zeros((3,2,2)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((5)) # define arreglos de n dimensiones lleno de unos
np.ones((5,3))
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [50]:
print(np.empty((5))) # define arreglos de n dimensiones lleno de ceros
print(np.empty((2,3))) # define arreglos de n dimensiones lleno con basura del 
print(np.zeros((3,2)))
print(np.empty((2,3,2)))

[1. 1. 1. 1. 1.]
[[0.000e+000 4.941e-324 9.881e-324]
 [4.931e-321 4.936e-321 4.941e-321]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[4.67433233e-310 3.16251369e+180]
  [8.82087199e+199 2.87289988e+257]
  [6.01428146e+175 2.87289953e+257]]

 [[2.87518202e+161 4.51545800e-144]
  [2.86530729e+161 5.31967571e+233]
  [6.32299171e+233 1.14366247e+243]]]


In [17]:
np.eye(4) #matriz identidad de nxn dimensiones

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
print(np.arange(12)) #crea un arreglo de numeros del tamaño especificado
print(np.arange(3,50)) #con 2 parámetros define inicio y fin
print(np.arange(4,20,2)) #con 3 parámetros define 

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 4  6  8 10 12 14 16 18]


In [23]:
arreglo_dimension = np.array([(1,2,3),(4,5,6)])
arreglo_dimension.shape

(2, 3)

In [29]:
np.arange(12).reshape(4,3) #cambia las dimensiones del arreglo a las definidas en el reshape

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
np.ones_like(np.arange(6).reshape(3,2)) 
np.ones_like(np.arange(6)) #llena de nuemros 1

array([1, 1, 1, 1, 1, 1])

In [32]:
np.arange(24).reshape(3,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [51]:
np.arange(10000)
np.arange(10000).reshape(100,10,10)
np.arange(1001)

array([   0,    1,    2, ...,  998,  999, 1000])

In [52]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [53]:
print(a+b) #suma de arreglos

[15 15 15]


In [54]:
print(a-b) #regla de arreglos

[5 5 5]


In [55]:
print(a*b) #multiplicacion de arreglos

[50 50 50]


In [57]:
print(a/b) #divicion de arreglos

[2. 2. 2.]


In [59]:
arreglo_dios_ocho = np.arange(18)
print(arreglo_dios_ocho)
print(arreglo_dios_ocho / 2) # division de cada valor del arreglo
print(arreglo_dios_ocho % 3) # modulo de cada valor del arreglo

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]


In [60]:
#Expresiones
print (arreglo_dios_ocho > 9)

[False False False False False False False False False False  True  True
  True  True  True  True  True  True]


In [84]:
#Multiplicacion de varias dimensiones (pero no es multiplicacion de matrices)
A = np.arange(4).reshape(2,2)
print ("A= ",A)
B = np.arange(4,8).reshape(2,2)
print ("B= ",B)

A * B


A=  [[0 1]
 [2 3]]
B=  [[4 5]
 [6 7]]


array([[ 0,  5],
       [12, 21]])

In [98]:
# Multiplicacione dot (multiplicacion de matrices)
A.dot(B)
C = np.zeros(4).reshape(2,2)
C = A.dot(B)
print(C)

[[ 6  7]
 [26 31]]


In [106]:
arreglo_diez_elementos = np.arange(10)
print(arreglo_diez_elementos)
print(arreglo_diez_elementos.sum())
print(arreglo_diez_elementos.min())
print(arreglo_diez_elementos.max())


[0 1 2 3 4 5 6 7 8 9]
45
0
9


In [104]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)
print(arreglo_tres_cuatro)
print(arreglo_tres_cuatro.sum(axis=0)) #suma en el eje X
print(arreglo_tres_cuatro.sum(axis=1)) #suma en el eje Y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


# universal functions
## radianes

In [117]:
angulos_cero_noventa = np.array([0,30,45,60,90])
print(angulos_cero_noventa)
angulos_cero_noventa_radianes = angulos_cero_noventa * np.pi/180
print(angulos_cero_noventa_radianes)
print("PI = ",np.pi)

[ 0 30 45 60 90]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
PI =  3.141592653589793


In [121]:
#Funcion seno
print("Seno",np.sin(angulos_cero_noventa))
print("Coseno",np.cos(angulos_cero_noventa))
print("Tangente",np.tan(angulos_cero_noventa))

Seno [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
Coseno [ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
Tangente [ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [141]:
#Media, Mediana, Moda
arreglo_diez_elementos = np.random.rand(30)*10
print(notas)
print(notas.mean())
print(np.median(arreglo_diez_elementos))
print()

[3.08602377 7.57525753 6.71276919 9.30553768 8.90268856 3.97755491
 5.99427496 2.20777084 2.68104661 0.76420278 3.3878174  2.84152266
 6.93048399 8.67480709 1.91695167 2.56726279 1.95731137 0.06464032
 2.53746418 0.69039733 5.18866528 0.47844567 6.54168833 5.36650066
 0.75359889 7.94049098 1.69526853 2.12077367 7.3629648  8.44888754]
4.289102333342617
3.361584266326508



In [145]:
#Desviacion Estandar
print(arreglo_diez_elementos)
print(np.std(arreglo_diez_elementos))

[5.56512607 8.98786287 2.52254916 7.33104226 9.19579976 4.25870163
 2.75009802 0.47902857 9.64546645 3.09637368 0.48462534 0.37737111
 1.85168568 7.50250974 0.69419464 5.18217582 2.03991001 0.13090478
 1.48506469 0.08502462 4.33955066 8.81104715 9.41898607 6.73829569
 0.65754798 3.62679485 8.82265767 2.65005394 5.92377307 2.82732187]
3.2103923528590452


In [146]:
#Varianza
print(arreglo_diez_elementos)
print(np.var(arreglo_diez_elementos))

[5.56512607 8.98786287 2.52254916 7.33104226 9.19579976 4.25870163
 2.75009802 0.47902857 9.64546645 3.09637368 0.48462534 0.37737111
 1.85168568 7.50250974 0.69419464 5.18217582 2.03991001 0.13090478
 1.48506469 0.08502462 4.33955066 8.81104715 9.41898607 6.73829569
 0.65754798 3.62679485 8.82265767 2.65005394 5.92377307 2.82732187]
10.306619059295837


In [158]:
#salarios
salarios = np.genfromtxt('data/salarios.csv',delimiter=',')
print(salarios)
print(salarios.shape)
print("Desviacion Estandar",np.std(salarios))
print("Varianza",np.var(salarios))

[[ 110.  250.  830.   40.  520.  123.  345.  123.  345.  132. 3245.  123.
   678.   23.  575.  234.  855.  121.]
 [ 110.  250.  830.   40.  520.  123.  345.  123.  345.  132. 3245.  123.
   678.   23.  575.  234.  855.  121.]
 [ 110.  250.  830.   40.  520.  123.  345.  123.  345.  132. 3245.  123.
   678.   23.  575.  234.  855.  121.]
 [ 110.  250.  830.   40.  520.  123.  345.  123.  345.  132. 3245.  123.
   678.   23.  575.  234.  855.  121.]
 [ 110.  250.  830.   40.  520.  123.  345.  123.  345.  132. 3245.  123.
   678.   23.  575.  234.  855.  121.]
 [ 110.  250.  830.   40.  520.  123.  345.  123.  345.  132. 3245.  123.
   678.   23.  575.  234.  855.  121.]
 [ 110.  250.  830.   40.  520.  123.  345.  123.  345.  132. 3245.  123.
   678.   23.  575.  234.  855.  121.]]
(7, 18)
Desviacion Estandar 718.0091732279652
Varianza 515537.1728395061


In [176]:
#Slice and Dice
arreglo_once_cuadrado = np.arange(11)**2
print(arreglo_once_cuadrado)
print(arreglo_once_cuadrado[0:3])
print(arreglo_once_cuadrado[-3])
print(arreglo_once_cuadrado[2:-3])
print(arreglo_once_cuadrado[-8:-1])
print(arreglo_once_cuadrado[1:])
print(arreglo_once_cuadrado[:5])
print(arreglo_once_cuadrado[:5])
print(arreglo_once_cuadrado[2:8:4])
print(arreglo_once_cuadrado[:10:2])
print(arreglo_once_cuadrado[::-1])

[  0   1   4   9  16  25  36  49  64  81 100]
[0 1 4]
64
[ 4  9 16 25 36 49]
[ 9 16 25 36 49 64 81]
[  1   4   9  16  25  36  49  64  81 100]
[ 0  1  4  9 16]
[ 0  1  4  9 16]
[ 4 36]
[ 0  4 16 36 64]
[100  81  64  49  36  25  16   9   4   1   0]


# Arange
Tenemos un arreglo de 10 elementos y queremos ahcer alguna cosa

In [6]:


estudiantes = np.array([['Adrian','Carlos','Vicente','Felipe'],
                       [1,2,3,4],
                       [6.5,7.5,8,9]
                      ]
                      )

In [7]:
estudiantes

array([['Adrian', 'Carlos', 'Vicente', 'Felipe'],
       ['1', '2', '3', '4'],
       ['6.5', '7.5', '8', '9']], dtype='<U7')

In [8]:
estudiantes.shape

(3, 4)

In [9]:
for estudiante in estudiantes:
    print(estudiante)  # Dimensiones

['Adrian' 'Carlos' 'Vicente' 'Felipe']
['1' '2' '3' '4']
['6.5' '7.5' '8' '9']


In [10]:
for estudiante in estudiantes.flatten():
    print(estudiante)  # 1-D

Adrian
Carlos
Vicente
Felipe
1
2
3
4
6.5
7.5
8
9


In [11]:
for estudiante in estudiantes.flatten(order='F'):
    print(estudiante)  # 1-D

Adrian
1
6.5
Carlos
2
7.5
Vicente
3
8
Felipe
4
9


In [12]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)
arreglo_tres_cuatro

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
# nditer
for i in np.nditer(arreglo_tres_cuatro):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [17]:
# nditer
for i in np.nditer(arreglo_tres_cuatro, order="F", op_flags=['readwrite']):
    print(i)
    i[...] = i*i
    print(i)

0
0
4
16
8
64
1
1
5
25
9
81
2
4
6
36
10
100
3
9
7
49
11
121


In [23]:
# Reshaping
paises_tuplas = np.array([('Ecuador','Colombia','Peru','Brazil'),
                          ('Mexico','Guatemala','Honduras','Venezuela')])

In [19]:
paises_tuplas

array([['Ecuador', 'Colombia', 'Peru', 'Brazil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [21]:
paises_tuplas[0][0] = 'Estados Unidos'

In [24]:
paises_tuplas[0][0]

'Ecuador'

In [25]:
paises_tuplas.shape

(2, 4)

In [26]:
paises_tuplas.flatten()

array(['Ecuador', 'Colombia', 'Peru', 'Brazil', 'Mexico', 'Guatemala',
       'Honduras', 'Venezuela'], dtype='<U9')

In [27]:
paises_tuplas.flatten().shape

(8,)

In [28]:
paises_tuplas

array([['Ecuador', 'Colombia', 'Peru', 'Brazil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [29]:
paises_tuplas.T

array([['Ecuador', 'Mexico'],
       ['Colombia', 'Guatemala'],
       ['Peru', 'Honduras'],
       ['Brazil', 'Venezuela']], dtype='<U9')

In [30]:
paises_tuplas.T.flatten()

array(['Ecuador', 'Mexico', 'Colombia', 'Guatemala', 'Peru', 'Honduras',
       'Brazil', 'Venezuela'], dtype='<U9')

In [36]:
paises_tuplas

array([['Ecuador', 'Colombia', 'Peru', 'Brazil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [37]:
paises_tuplas.reshape(4,2)

array([['Ecuador', 'Colombia'],
       ['Peru', 'Brazil'],
       ['Mexico', 'Guatemala'],
       ['Honduras', 'Venezuela']], dtype='<U9')

In [42]:
paises = np.array(['Ecuador',
                   'Colombia',
                   'Peru',
                   'Brazil',
                   'Mexico',
                   'Guatemala',
                   'Honduras',
                   'Venezuela',
                   'Argentina',
                   'Chile',
                   'Bolivia',
                   'Alemania'])

In [44]:
paises.reshape(3,-1,2)  #  9    9 = X * 3    X = 9/3 = 3

array([[['Ecuador', 'Colombia'],
        ['Peru', 'Brazil']],

       [['Mexico', 'Guatemala'],
        ['Honduras', 'Venezuela']],

       [['Argentina', 'Chile'],
        ['Bolivia', 'Alemania']]], dtype='<U9')

In [ ]:
# Split

In [51]:
arreglo_split = np.arange(1,13)

In [54]:
arreglo_split.shape

(12,)

In [52]:
np.split(arreglo_split,[2,3,5,7,8])

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [63]:
array_split_4_partes = np.array(array_split_4_partes)

In [66]:
array_split_4_partes.shape

(5,)

In [67]:
paises = np.array(['Ecuador',
                   'Colombia',
                   'Peru',
                   'Brazil',
                   'Mexico',
                   'Guatemala'])

In [69]:
np.hsplit(paises,2)

[array(['Ecuador', 'Colombia', 'Peru'], dtype='<U9'),
 array(['Brazil', 'Mexico', 'Guatemala'], dtype='<U9')]

In [70]:
np.split(paises,2)

[array(['Ecuador', 'Colombia', 'Peru'], dtype='<U9'),
 array(['Brazil', 'Mexico', 'Guatemala'], dtype='<U9')]

In [74]:
paises_2d = np.array([['Ecuador',
                   'Colombia',
                   'Peru'], 
                   ['Brazil',
                   'Mexico',
                   'Guatemala']])

In [76]:
print(paises_2d.shape)
np.vsplit(paises_2d,2)

(2, 3)


[array([['Ecuador', 'Colombia', 'Peru']], dtype='<U9'),
 array([['Brazil', 'Mexico', 'Guatemala']], dtype='<U9')]

In [78]:
np.hsplit(paises_2d,3)

[array([['Ecuador'],
        ['Brazil']], dtype='<U9'), array([['Colombia'],
        ['Mexico']], dtype='<U9'), array([['Peru'],
        ['Guatemala']], dtype='<U9')]