In [1]:
import numpy as np

In [2]:
arreglo_diez_seis = np. arange(16).reshape(4,4)
arreglo_diez_seis

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
indice_booleano_mayores_a_ocho = arreglo_diez_seis > 8
indice_booleano_mayores_a_ocho

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [5]:
print(arreglo_diez_seis [indice_booleano_mayores_a_ocho]) # si se empata una matriz booleana se 
                                                          #despliega los objetos que cumplen esa condicion

[ 9 10 11 12 13 14 15]


In [9]:
print(np.count_nonzero(indice_booleano_mayores_a_ocho)) # cuenta los elementos que cumplen la condición

7


In [10]:
print(np.sum(indice_booleano_mayores_a_ocho))

7


In [15]:
print(np.sum(indice_booleano_mayores_a_ocho, axis = 1).reshape(4,1))

[[0]
 [0]
 [3]
 [4]]


In [19]:
indice_booleano_mayor_a_veinte = arreglo_diez_seis > 20
print(np.any(indice_booleano_mayor_a_veinte)) # verifica si alguno cumple

False
