# Ejercicios Matemáticos

In [1]:
import numpy as np

In [15]:
A = np.array([[1.,3.,2.],[1.,0.,0.],[1.,2.,2.]]) # Matriz A
print(A)

[[1. 3. 2.]
 [1. 0. 0.]
 [1. 2. 2.]]


In [16]:
B = np.array([[1.,0.,5.],[7.,5.,0.],[2.,1.,1.]]) # Matriz B
print(B)

[[1. 0. 5.]
 [7. 5. 0.]
 [2. 1. 1.]]


In [17]:
I = np.eye(3,3) # Matriz Identidad
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
A_inv=np.linalg.inv(A) # Matriz Inversa de A
print(A_inv)

[[-4.4408921e-16  1.0000000e+00  0.0000000e+00]
 [ 1.0000000e+00 -0.0000000e+00 -1.0000000e+00]
 [-1.0000000e+00 -5.0000000e-01  1.5000000e+00]]


## Suma de matrices

In [19]:
A + B

array([[2., 3., 7.],
       [8., 5., 0.],
       [3., 3., 3.]])

## Resta de matrices

In [20]:
A - B 

array([[ 0.,  3., -3.],
       [-6., -5.,  0.],
       [-1.,  1.,  1.]])

## Multiplicación matriz por escalar

In [21]:
A * 7 

array([[ 7., 21., 14.],
       [ 7.,  0.,  0.],
       [ 7., 14., 14.]])

## Multiplicación de matrices

In [22]:
A @ B # A x B

array([[26., 17.,  7.],
       [ 1.,  0.,  5.],
       [19., 12.,  7.]])

In [23]:
B @ A # B x A

array([[ 6., 13., 12.],
       [12., 21., 14.],
       [ 4.,  8.,  6.]])

In [24]:
A @ I # A x I = A #Matriz x identidad

array([[1., 3., 2.],
       [1., 0., 0.],
       [1., 2., 2.]])

In [25]:
A @ A_inv # A x A_inv = I

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [-4.4408921e-16,  1.0000000e+00,  0.0000000e+00],
       [-4.4408921e-16,  0.0000000e+00,  1.0000000e+00]])

In [57]:
 print(np.linalg.det(A)) #identidad

1.0000000000000009


In [32]:
#Transpuesta de una matriz
print("Matriz A\n",A)
A_trans = np.transpose(A)
print("\nA transpuesta\n",A_trans)

Matriz A
 [[1. 3. 2.]
 [1. 0. 0.]
 [1. 2. 2.]]

A transpuesta
 [[1. 1. 1.]
 [3. 0. 2.]
 [2. 0. 2.]]


In [41]:
c = np.array([[6],[4],[2]]) #matriz de resultados
print(c)

[[6]
 [4]
 [2]]


In [50]:
x = np.linalg.solve(A,c) # resolviendo sistema de ecuaciones A,c 
print(x)

[[ 4.]
 [ 4.]
 [-5.]]


In [51]:
 A @ x == c #comprobando la solución

array([[False],
       [False],
       [False]])

## Comprobar si una matriz es inversible

In [69]:
A = np.array([[2.,1.],[5.,3.]]) #matriz 2x2
print (A)
A.shape

[[2. 1.]
 [5. 3.]]


(2, 2)

In [70]:
A_inv = np.linalg.inv(A) # inversa de A
print("A inversa",A_inv)

A inversa [[ 3. -1.]
 [-5.  2.]]


In [71]:
A_det = np.linalg.det(A)
print(A_det) # determinante de A

1.0000000000000009


In [73]:
if(round(1/A_det)!=0):
    print("Es invertible")
else:
    print("Matriz Singular/degenerada")
    

Es invertible


## Serie de Taylor